# Generated by Django 4.1 on 2022-09-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": (
                    ("product.can_change_product_name", "Can change product name"),
                    (
                        "product.can_change_product_category",
                        "Can change product category",
                    ),
                )
            },
        ),
    ]
