# Generated by Django 4.1 on 2022-09-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": (
                    ("can_change_product_name", "Can change product name"),
                    ("can_change_product_category", "Can change product category"),
                )
            },
        ),
    ]
