# Generated by Django 4.1 on 2022-08-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onlinepayment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="onlinepayment",
            index=models.Index(
                fields=["-created_at"], name="online_paym_created_8e7797_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlinepayment",
            index=models.Index(fields=["status"], name="online_paym_status_c8aeaf_idx"),
        ),
        migrations.AlterModelTable(
            name="onlinepayment",
            table="online_payments",
        ),
    ]
